/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestSensorsRouteImport } from './routes/test.sensors'
import { Route as TestMediaRouteImport } from './routes/test.media'
import { Route as TestDisplayRouteImport } from './routes/test.display'
import { Route as TestBatteryRouteImport } from './routes/test.battery'

const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSensorsRoute = TestSensorsRouteImport.update({
  id: '/test/sensors',
  path: '/test/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const TestMediaRoute = TestMediaRouteImport.update({
  id: '/test/media',
  path: '/test/media',
  getParentRoute: () => rootRouteImport,
} as any)
const TestDisplayRoute = TestDisplayRouteImport.update({
  id: '/test/display',
  path: '/test/display',
  getParentRoute: () => rootRouteImport,
} as any)
const TestBatteryRoute = TestBatteryRouteImport.update({
  id: '/test/battery',
  path: '/test/battery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/test/battery': typeof TestBatteryRoute
  '/test/display': typeof TestDisplayRoute
  '/test/media': typeof TestMediaRoute
  '/test/sensors': typeof TestSensorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/test/battery': typeof TestBatteryRoute
  '/test/display': typeof TestDisplayRoute
  '/test/media': typeof TestMediaRoute
  '/test/sensors': typeof TestSensorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/test/battery': typeof TestBatteryRoute
  '/test/display': typeof TestDisplayRoute
  '/test/media': typeof TestMediaRoute
  '/test/sensors': typeof TestSensorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostico'
    | '/test/battery'
    | '/test/display'
    | '/test/media'
    | '/test/sensors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostico'
    | '/test/battery'
    | '/test/display'
    | '/test/media'
    | '/test/sensors'
  id:
    | '__root__'
    | '/'
    | '/diagnostico'
    | '/test/battery'
    | '/test/display'
    | '/test/media'
    | '/test/sensors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  TestBatteryRoute: typeof TestBatteryRoute
  TestDisplayRoute: typeof TestDisplayRoute
  TestMediaRoute: typeof TestMediaRoute
  TestSensorsRoute: typeof TestSensorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/sensors': {
      id: '/test/sensors'
      path: '/test/sensors'
      fullPath: '/test/sensors'
      preLoaderRoute: typeof TestSensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/media': {
      id: '/test/media'
      path: '/test/media'
      fullPath: '/test/media'
      preLoaderRoute: typeof TestMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/display': {
      id: '/test/display'
      path: '/test/display'
      fullPath: '/test/display'
      preLoaderRoute: typeof TestDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/battery': {
      id: '/test/battery'
      path: '/test/battery'
      fullPath: '/test/battery'
      preLoaderRoute: typeof TestBatteryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  TestBatteryRoute: TestBatteryRoute,
  TestDisplayRoute: TestDisplayRoute,
  TestMediaRoute: TestMediaRoute,
  TestSensorsRoute: TestSensorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
